//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.25 at 12:18:08 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.samples.blog.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.blog.samples.webservices;
